### ISSUE TITLE
Won't compile with Visual Studio 2019 16.3

### ISSUE THREAD

**Issue by ZeikoRomsan1** [uNetworking/uWebSockets#940]
uWebSockets won't compile with Visual Studio 2019 16.3, 16.2 works good.

Error in VS 16.3:
uWebSockets\f2\function2.hpp(705,1):

error C2440: 'static_cast': cannot convert from 'fu2::abi_400::detail::type_erasure::erasure<true,Config,fu2::abi_400::detail::property<true,false,void *(void *)>>' to 'erasure_t &'
error C2440:         with
error C2440:         [
error C2440:             Config=fu2::abi_400::detail::config<true,false,fu2::capacity_default>
error C2440:         ]

Boost: 1.70.0
LIBUS_NO_SSL
LIBUS_USE_LIBUV
Version: v0.16.0b2
Commit: bc6ea664b17fb3736e1330e908aee00c4f3a750b
Visual Studio 2019 16.3

**Comment by alexhultman** [comment]
So the solution is to update function2?

**Comment by ZeikoRomsan1** [comment]
@alexhultman 
Yes thats correct, uwebsockets works good after upgrading f2\function2.hpp with commit: 7cd95374b0f1c941892bfc40f0ebb6564d33fdb9

**Comment by alexhultman** [comment]
Updated
