### ISSUE TITLE
lws.cpp won't compile in benchmarks

### ISSUE THREAD

**Issue by chriscurrym2** [uNetworking/uWebSockets#716]
Running the lws build on its own using the following command:

`$ g++ -v -std=c++11 -O3 lws.cpp -o lws /usr/local/lib/libwebsockets.a -lev -lssl -lz -lcrypto`

I get the following errors:

`lws.cpp: In function 'int main(int, char**)':
lws.cpp:138:46: error: 'ev_default_loop' was not declared in this scope
     lws_ev_initloop(context, ev_default_loop(), 0);`
                                              
`lws.cpp:138:50: error: 'lws_ev_initloop' was not declared in this scope
     lws_ev_initloop(context, ev_default_loop(), 0);`
                                                  
`lws.cpp:139:29: error: 'ev_run' was not declared in this scope
     ev_run(ev_default_loop());`

Versions:
libuWS - 0.14.4
libwebsockets - 2.3
libev - 4.22

OS - WindRiver Pulsar Linux
Arch - ARMv7-A

**Comment by alexhultman** [comment]
If you want to update the lws benchmark I could merge it

**Comment by chriscurrym2** [comment]
Working on it now - there's an issue with beast too, looks like they refactored their file/directory names. I'll change the Makefile, beast.cpp, and lws.cpp and put in a PR.

**Comment by chriscurrym2** [comment]
Okay - so I've modified the Makefile, but when I attempt to build I'm getting an undefined reference to lws_ev_initloop which seems to be due to how I built libwebsockets initially. libwebsockets won't link when I enable libev support through CMake; I just saw you were having similar issues (https://github.com/warmcat/libwebsockets/issues/546), did you figure out how to get libwebsockets to correctly compile and link with the -DLWS_USE_LIBEV flag?

**Comment by alexhultman** [comment]
If you cannot solve it yourself then we close it
