### ISSUE TITLE
C++23 Support

### ISSUE THREAD

**Issue by AndrewSerra** [uNetworking/uWebSockets#1907]
Our codebase is migrating up to C++23 and we are getting the following error.

```
include/uWebSockets/ChunkedEncoding.h:219:17: error: no member named 'abort' in namespace 'std'; did you mean simply 'abort'?

  219 |                 std::abort();

      |                 ^~~~~
```

We validated that the builds were successful when using C++17 and C++20. When bumped to 23, the error shows up and there is no way to configure it easily to work in the current state. This error only occurs on iOS and iOS simulator build not Linux, Android, etc.

If there are ways around it, we would love to know about it. We are using Conan 2.25 and uWebSockets version 20.71.0.

**Comment by uNetworkingAB** [comment]
Should be fixed now
