### ISSUE TITLE
Doesn't compile in the Visual Studio 2019 (20.34.0)

### ISSUE THREAD

**Issue by bitmakerneo** [uNetworking/uWebSockets#1549]
The uWebSockets (20.34.0) does not compile in the Visual Studio 2019.

Error C3861 'us_socket_context_on_long_timeout': identifier not found WebSocketContext.h, 374	

![image](https://user-images.githubusercontent.com/13796179/211210511-a3d9bb45-a4e5-48ad-8be6-5850eba29f88.png)
![image](https://user-images.githubusercontent.com/13796179/211210519-ca3f4e70-b4c9-411e-9658-36c8d7fc1640.png)

**Comment by uNetworkingAB** [comment]
You need a newer uSockets

**Comment by bitmakerneo** [comment]
The vcpkg only offers to install version 0.8.3, although version 0.8.5 is already available.
![image](https://user-images.githubusercontent.com/13796179/211257793-967aba26-6528-4dc3-95aa-a18b71767921.png)
![image](https://user-images.githubusercontent.com/13796179/211257368-a0f502e4-8871-4e7e-9f09-3877edad359f.png)

**Comment by bitmakerneo** [comment]
**Thank you!**

![image](https://user-images.githubusercontent.com/13796179/212288710-44aa9292-ee1f-4888-b86f-0398cd766161.png)
![image](https://user-images.githubusercontent.com/13796179/212288722-cb9e5cb3-98cd-4e46-8917-2ce664572cb1.png)
![image](https://user-images.githubusercontent.com/13796179/212288739-360f1773-8c0e-4ed9-b549-2f909034c152.png)
